# ---- deps ----------------------------------------------------------------
FROM node:24-alpine AS deps
WORKDIR /app

RUN corepack enable

COPY package.json pnpm-lock.yaml* ./
RUN pnpm install --frozen-lockfile --ignore-scripts

# ---- build ---------------------------------------------------------------
FROM node:24-alpine AS builder
WORKDIR /app

RUN corepack enable
ENV NEXT_TELEMETRY_DISABLED=1

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Build-time config: NEXT_PUBLIC_* vars are inlined into the client bundle.
ARG NEXT_PUBLIC_API_BASE_URL=https://cms-gateway.polskieradio.pl/dev-proxy
ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL

RUN pnpm build

# ---- runtime -------------------------------------------------------------
FROM node:24-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

# Runtime config (server-side route handlers read this at request time).
ARG NEXT_PUBLIC_API_BASE_URL=https://cms-gateway.polskieradio.pl/dev-proxy
ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL

RUN addgroup --system --gid 1001 nodejs \
  && adduser  --system --uid 1001 nextjs

# `output: 'standalone'` emits a self-contained server at .next/standalone.
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/public ./public

USER nextjs

EXPOSE 3000

# `server.js` is generated by Next.js at .next/standalone/server.js
CMD ["node", "server.js"]
